### PR TITLE
Add ResolutionTypeCreated event

### PR DESCRIPTION
**Pull request by sirnicolaz**
This way, when the contract is deployed, our Subgraph can automatically fetch the static information related to the DAO (like resolution types).

### CODE REVIEW

**Comment by vrde** [comment]
How do we make subgraph listen to this event if the contract doesn't have an address yet?

**Comment by sirnicolaz** [comment]
Subgraph can listen to old events as well. So as soon as we deploy the subgraph, it will catch it

**Comment by vrde** [comment]
Right. I think it's better to have an event per ResolutionType.

**Comment by sirnicolaz** [comment]
does the PR satisfies you now @vrde ?

**Review by vrde — APPROVED** [review]

**Pull request merged**
